# Generated by Django 5.1.6 on 2026-09-04 06:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leavetype_rosterentry_attendance_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('requested_by_user_id', models.UUIDField()),
                ('fields_payload', models.JSONField(default=dict, help_text='Dictionary of proposed field changes.')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('decided_by_user_id', models.UUIDField(blank=True, null=True)),
                ('decided_by_name', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_profile_correction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reason', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending_peer', 'Pending colleague acceptance'), ('pending_manager', 'Pending manager approval'), ('approved', 'Approved'), ('rejected_peer', 'Declined by colleague'), ('rejected_manager', 'Declined by manager'), ('cancelled', 'Cancelled')], db_index=True, default='pending_peer', max_length=20)),
                ('peer_notes', models.CharField(blank=True, max_length=255)),
                ('peer_decided_at', models.DateTimeField(blank=True, null=True)),
                ('manager_user_id', models.UUIDField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('manager_notes', models.CharField(blank=True, max_length=255)),
                ('manager_decided_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_swap_requests', to='hr.employee')),
                ('requester_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_swaps', to='hr.rosterentry')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_swap_requests', to='hr.employee')),
                ('target_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_swaps', to='hr.rosterentry')),
            ],
            options={
                'db_table': 'hr_shift_swap',
                'ordering': ['-created_at'],
            },
        ),
    ]
