# Generated by Django 5.1.6 on 2026-09-14 19:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('test_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('modality', models.CharField(blank=True, max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diagnostic_report_template',
                'ordering': ['name'],
            },
        ),
    ]
