# Generated by Django 5.1.6 on 2026-09-04 11:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('approval', 'Approval'), ('task', 'Task'), ('reminder', 'Reminder'), ('information', 'Information')], db_index=True, default='information', max_length=16)),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=1024)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=48)),
                ('subject_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_reason', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='organization.facility')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('approval', 'Approval'), ('task', 'Task'), ('reminder', 'Reminder'), ('information', 'Information')], max_length=16)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'category', 'channel'), name='uniq_preference_per_owner_category_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=16)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dismissed_note', models.CharField(blank=True, max_length=255)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.notification')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source', 'event', 'raised_at'], name='notificatio_source_4330f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'resolved_at'], name='notificatio_categor_a4cf70_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True), models.Q(('dedupe_key', ''), _negated=True)), fields=('dedupe_key',), name='uniq_open_notification_per_dedupe_key'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('raised_at')), _connector='OR'), name='notification_resolved_after_raised'),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['recipient_id', 'read_at'], name='notificatio_recipie_84a8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['recipient_id', 'dismissed_at'], name='notificatio_recipie_ca75f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.UniqueConstraint(fields=('notification', 'recipient_id'), name='uniq_receipt_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('dismissed_at__isnull', True), ('read_at__isnull', False), _connector='OR'), name='receipt_dismissed_implies_read'),
        ),
    ]
