# Generated by Django 5.1.6 on 2026-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_open_notification_per_dedupe_key',
        ),
        migrations.RemoveConstraint(
            model_name='notificationreceipt',
            name='uniq_receipt_per_recipient',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True), ('deleted_at__isnull', True), models.Q(('dedupe_key', ''), _negated=True)), fields=('dedupe_key',), name='uniq_open_notification_per_dedupe_key'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('notification', 'recipient_id'), name='uniq_receipt_per_recipient'),
        ),
    ]
