# Generated by Django 5.1.6 on 2026-09-14 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_constraints_respect_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('unreachable', 'No way to reach them'), ('declined', 'Turned off by the recipient')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationreceipt')),
            ],
            options={
                'db_table': 'notification_delivery',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('receipt', 'channel'), name='uniq_delivery_per_channel')],
            },
        ),
    ]
