# Generated by Django 5.1.6 on 2026-09-14 16:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_delivery'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('appointment', 'Appointment reminder'), ('result_ready', 'Result ready'), ('bill_due', 'Bill outstanding')], max_length=24)),
                ('channel', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='ne', max_length=8)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('unreachable', 'No way to reach them'), ('declined', 'The patient asked not to be contacted')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='patient_mes_patient_bf81c5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dedupe_key',), name='uniq_patient_message_key')],
            },
        ),
    ]
