# Generated by Django 5.1.6 on 2026-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_patient_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmessage',
            name='kind',
            field=models.CharField(choices=[('appointment', 'Appointment reminder'), ('result_ready', 'Result ready'), ('bill_due', 'Bill outstanding'), ('follow_up', 'Follow-up due')], max_length=24),
        ),
    ]
