# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(help_text='Immutable. Used for the tenant database name and subdomain.', unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{2,48}$', 'Use lowercase letters, digits and underscores; must start with a letter.')])),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('diagnostic', 'Diagnostic centre'), ('polyclinic', 'Polyclinic'), ('chain', 'Multi-branch chain'), ('group', 'Healthcare group'), ('distributor', 'Pharmaceutical distributor')], default='clinic', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending provisioning'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('municipality', models.CharField(blank=True, max_length=128)),
                ('ward', models.CharField(blank=True, max_length=16)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=4)),
                ('fiscal_year_start_day', models.PositiveSmallIntegerField(default=1)),
                ('uses_bikram_sambat', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=9)),
                ('locale', models.CharField(default='en-NP', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cp_organization',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['status', 'business_type'], name='cp_organiza_status_c94a8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('alias', models.CharField(help_text='Django connection alias, e.g. tenant_manakamana.', max_length=64, unique=True)),
                ('db_name', models.CharField(max_length=128, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(default='5432', max_length=8)),
                ('db_user', models.CharField(max_length=128)),
                ('db_password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending creation'), ('provisioning', 'Provisioning'), ('migrating', 'Migrating'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('last_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('region', models.CharField(default='default', max_length=64)),
                ('is_read_only', models.BooleanField(default=False)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('backup_location', models.CharField(blank=True, max_length=512)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='database', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_tenant_database',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('facility_uuid', models.UUIDField(unique=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('diagnostic', 'Diagnostic centre'), ('warehouse', 'Warehouse'), ('corporate_office', 'Corporate office'), ('other', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('municipality', models.CharField(blank=True, max_length=128)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_registry', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_facility_registry',
                'ordering': ['organization_id', 'name'],
                'indexes': [models.Index(fields=['organization', 'facility_type', 'status'], name='cp_facility_organiz_b6bdab_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_facility_code_per_org')],
            },
        ),
    ]
