# Generated by Django 5.1.6 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facilityregistryentry',
            name='uniq_facility_code_per_org',
        ),
        migrations.AddConstraint(
            model_name='facilityregistryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_facility_code_per_org'),
        ),
    ]
