# Generated by Django 5.1.6 on 2026-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('patients', '0001_initial'),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surgicalcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_end__isnull', True), ('scheduled_start__isnull', True)), models.Q(('scheduled_end__isnull', False), ('scheduled_start__isnull', False)), _connector='OR'), name='ot_case_slot_has_both_ends'),
        ),
    ]
