# Generated by Django 5.1.6 on 2026-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_product_vat_rate'),
        ('theatre', '0002_surgicalcase_ot_case_slot_has_both_ends'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caseconsumption',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kind', 'implant'), models.Q(('serial_number', ''), _negated=True)), fields=('serial_number',), name='uniq_implant_serial'),
        ),
    ]
