# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed login'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('view_sensitive', 'View sensitive record'), ('export', 'Export'), ('print', 'Print'), ('download', 'Download'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('cancel', 'Cancel'), ('refund', 'Refund'), ('stock_adjust', 'Stock adjustment'), ('prescription_change', 'Prescription change'), ('patient_merge', 'Patient merge'), ('payroll_change', 'Payroll change'), ('permission_change', 'Permission change'), ('config_change', 'Configuration change'), ('facility_change', 'Facility change'), ('support_access', 'Platform support access')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('notable', 'Notable'), ('sensitive', 'Sensitive'), ('critical', 'Critical')], default='info', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=128)),
                ('is_platform_actor', models.BooleanField(default=False)),
                ('on_behalf_of_id', models.UUIDField(blank=True, null=True)),
                ('facility_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=32)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, help_text='Human-readable at the time of the event, since the record may since have been renamed or deleted.', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Correlates every event produced by one request.', max_length=64)),
                ('http_method', models.CharField(blank=True, max_length=8)),
                ('http_path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='audit_event_entity__a0e919_idx'), models.Index(fields=['actor_id', '-occurred_at'], name='audit_event_actor_i_279070_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_event_action_3ba322_idx'), models.Index(fields=['severity', '-occurred_at'], name='audit_event_severit_92682f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=128)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_email', models.CharField(blank=True, max_length=254)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_reason', models.TextField(blank=True)),
                ('audit_event_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entity_version',
                'ordering': ['entity_type', 'entity_id', '-version'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-version'], name='entity_vers_entity__84ad24_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'version'), name='uniq_entity_version')],
            },
        ),
    ]
