# Generated by Django 5.1.6 on 2026-09-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='facility_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
