# Generated by Django 5.1.6 on 2026-09-11 21:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_number_sequence_facility_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('provider', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('initiated', 'Started'), ('pending', 'Pending'), ('completed', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=12)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('provider_transaction', models.CharField(blank=True, max_length=64)),
                ('payment_url', models.URLField(blank=True, max_length=512)),
                ('channel', models.CharField(default='portal', max_length=12)),
                ('started_by_name', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('needs_attention', models.CharField(blank=True, max_length=255)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='billing.invoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_payment', to='billing.payment')),
            ],
            options={
                'db_table': 'online_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'reference'], name='online_paym_provide_638e66_idx'), models.Index(fields=['status', '-created_at'], name='online_paym_status_f6b95e_idx')],
            },
        ),
    ]
