# Generated by Django 5.1.6 on 2026-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_planfeature_uniq_feature_per_plan_and_more'),
        ('subscriptions', '0001_initial'),
        ('tenancy', '0002_remove_facilityregistryentry_uniq_facility_code_per_org_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['trialing', 'active', 'past_due', 'grace'])), fields=('organization',), name='one_live_subscription_per_organization'),
        ),
    ]
