# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMeterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(default='count', max_length=32)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum over the period'), ('max', 'Peak during the period'), ('last', 'Value at period end')], default='sum', max_length=8)),
                ('limit_key', models.CharField(blank=True, max_length=128)),
                ('is_billable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cp_usage_meter_definition',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=False, help_text='Included in every plan and cannot be disabled.')),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='catalog.module')),
            ],
            options={
                'db_table': 'cp_module',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.module')),
            ],
            options={
                'db_table': 'cp_feature',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('annual', 'Annual'), ('custom', 'Custom contract')], default='monthly', max_length=16)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('grace_days', models.PositiveSmallIntegerField(default=7)),
                ('is_public', models.BooleanField(default=True, help_text='Listed on pricing pages. Custom deals are private.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='catalog.plan')),
            ],
            options={
                'db_table': 'cp_plan',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('limit_increment', 'Increases a limit'), ('module', 'Adds a module'), ('feature', 'Enables a feature')], max_length=32)),
                ('target_key', models.CharField(db_index=True, max_length=128)),
                ('increment', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('annual', 'Annual'), ('custom', 'Custom contract')], default='monthly', max_length=16)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Platform staff must approve before this add-on takes effect.')),
                ('is_active', models.BooleanField(default=True)),
                ('available_on_plans', models.ManyToManyField(blank=True, related_name='available_addons', to='catalog.plan')),
            ],
            options={
                'db_table': 'cp_addon',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='catalog.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='catalog.plan')),
            ],
            options={
                'db_table': 'cp_plan_feature',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='plans', through='catalog.PlanFeature', to='catalog.feature'),
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('value', models.IntegerField(blank=True, help_text='NULL means unlimited.', null=True)),
                ('enforcement', models.CharField(choices=[('hard', 'Block the action'), ('soft', 'Allow, flag for review'), ('grace', 'Allow within grace window, then block'), ('metered', 'Allow and bill the overage')], default='hard', max_length=16)),
                ('overage_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=80)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='catalog.plan')),
            ],
            options={
                'db_table': 'cp_plan_limit',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_included', models.BooleanField(default=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.module')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='catalog.plan')),
            ],
            options={
                'db_table': 'cp_plan_module',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.ManyToManyField(related_name='plans', through='catalog.PlanModule', to='catalog.module'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='uniq_feature_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan', 'key'), name='uniq_limit_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planmodule',
            constraint=models.UniqueConstraint(fields=('plan', 'module'), name='uniq_module_per_plan'),
        ),
    ]
