# Generated by Django 5.1.6 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planfeature',
            name='uniq_feature_per_plan',
        ),
        migrations.RemoveConstraint(
            model_name='planlimit',
            name='uniq_limit_per_plan',
        ),
        migrations.RemoveConstraint(
            model_name='planmodule',
            name='uniq_module_per_plan',
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'feature'), name='uniq_feature_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'key'), name='uniq_limit_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='planmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'module'), name='uniq_module_per_plan'),
        ),
    ]
