# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_superuser_role', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('max_scope', models.CharField(choices=[('own', 'Own records'), ('own_patients', 'Own patients'), ('unit', 'Own unit'), ('department', 'Own department'), ('facility', 'Own facility'), ('multi_facility', 'Assigned facilities'), ('organization', 'Whole organization')], default='facility', max_length=24)),
                ('requires_approval_to_assign', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('inherits_from', models.ManyToManyField(blank=True, related_name='inherited_by', to='rbac.role')),
            ],
            options={
                'db_table': 'role',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('permission_code', models.CharField(db_index=True, max_length=64)),
                ('is_granted', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('own', 'Own records'), ('own_patients', 'Own patients'), ('unit', 'Own unit'), ('department', 'Own department'), ('facility', 'Own facility'), ('multi_facility', 'Assigned facilities'), ('organization', 'Whole organization')], default='facility', max_length=24)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Required: why this person deviates from role.')),
                ('granted_by_id', models.UUIDField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.facility')),
            ],
            options={
                'db_table': 'permission_override',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'permission_code'], name='permission__user_id_2264ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_email', models.CharField(blank=True, help_text='Denormalised for display, so listing assignments needs no cross-database lookup.', max_length=254)),
                ('scope', models.CharField(choices=[('own', 'Own records'), ('own_patients', 'Own patients'), ('unit', 'Own unit'), ('department', 'Own department'), ('facility', 'Own facility'), ('multi_facility', 'Assigned facilities'), ('organization', 'Whole organization')], default='facility', max_length=24)),
                ('facility_uuids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('assigned_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organization.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organization.facility')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac.role')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organization.unit')),
            ],
            options={
                'db_table': 'role_assignment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='role_assign_user_id_a81ab4_idx'), models.Index(fields=['role', 'status'], name='role_assign_role_id_2b4d30_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_id', 'role', 'scope', 'facility', 'department', 'unit'), name='uniq_active_role_assignment')],
            },
        ),
    ]
