# Generated by Django 5.1.6 on 2026-09-05 19:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakGlassGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('patient_uuid', models.UUIDField(db_index=True)),
                ('patient_label', models.CharField(blank=True, help_text='Name and MRN as they stood when the record was opened.', max_length=255)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_label', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=512)),
                ('granted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Awaiting review'), ('appropriate', 'Appropriate'), ('queried', 'Queried with the clinician'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=16)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'break_glass_grant',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user_id', 'patient_uuid', 'expires_at'], name='break_glass_user_id_de2342_idx'), models.Index(fields=['outcome', '-granted_at'], name='break_glass_outcome_44e950_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('granted_at'))), name='break_glass_expires_after_it_is_granted'), models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'pending'), ('reviewed_at__isnull', True)), ('reviewed_at__isnull', False), _connector='OR'), name='break_glass_decided_means_reviewed')],
            },
        ),
    ]
