# Generated by Django 5.1.6 on 2026-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_break_glass_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='grantable_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
