# Generated by Django 5.1.6 on 2026-09-14 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('author_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('urgent', models.BooleanField(default=False)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_messages', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_care_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='patient_car_patient_85d8bc_idx')],
            },
        ),
    ]
