# Generated by Django 5.1.6 on 2026-09-03 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('arrived_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('arrival_mode', models.CharField(choices=[('walk_in', 'Walked in'), ('ambulance', 'Ambulance'), ('private_vehicle', 'Private vehicle'), ('police', 'Police'), ('referred', 'Referred from another facility'), ('helicopter', 'Air ambulance'), ('other', 'Other')], db_index=True, default='walk_in', max_length=20)),
                ('ambulance_reference', models.CharField(blank=True, max_length=64)),
                ('brought_by', models.CharField(blank=True, max_length=255)),
                ('brought_by_phone', models.CharField(blank=True, max_length=32)),
                ('presenting_complaint', models.CharField(max_length=512)),
                ('is_unidentified', models.BooleanField(db_index=True, default=False)),
                ('provisional_description', models.CharField(blank=True, max_length=255)),
                ('triage_category', models.IntegerField(blank=True, choices=[(1, '1 — Resuscitation (immediate)'), (2, '2 — Emergent (within 10 minutes)'), (3, '3 — Urgent (within 30 minutes)'), (4, '4 — Less urgent (within 60 minutes)'), (5, '5 — Non-urgent (within 120 minutes)')], db_index=True, null=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seen_by_id', models.UUIDField(blank=True, null=True)),
                ('seen_by_name', models.CharField(blank=True, max_length=255)),
                ('disposition', models.CharField(choices=[('pending', 'Still in the department'), ('discharged', 'Discharged home'), ('admitted', 'Admitted'), ('referred', 'Referred to another facility'), ('lwbs', 'Left without being seen'), ('lama', 'Left against medical advice'), ('absconded', 'Absconded'), ('died', 'Died in the department'), ('brought_dead', 'Brought in dead')], db_index=True, default='pending', max_length=16)),
                ('disposition_at', models.DateTimeField(blank=True, null=True)),
                ('disposition_notes', models.TextField(blank=True)),
                ('admission_reference', models.CharField(blank=True, max_length=32)),
                ('referred_to', models.CharField(blank=True, max_length=255)),
                ('is_mlc', models.BooleanField(default=False, help_text='Medico-legal: assault, accident, poisoning, burns.')),
                ('mlc_number', models.CharField(blank=True, max_length=64)),
                ('police_informed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='organization.department')),
                ('encounter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival', to='encounters.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='organization.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='patients.patient')),
            ],
            options={
                'db_table': 'ed_arrival',
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='CriticalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('pathway', models.CharField(choices=[('stemi', 'STEMI — heart attack'), ('stroke', 'Stroke'), ('sepsis', 'Sepsis'), ('trauma', 'Major trauma'), ('cardiac_arrest', 'Cardiac arrest'), ('obstetric', 'Obstetric emergency'), ('paediatric', 'Paediatric emergency'), ('poisoning', 'Poisoning'), ('burn', 'Major burn')], db_index=True, max_length=20)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_by_id', models.UUIDField(blank=True, null=True)),
                ('activated_by_name', models.CharField(blank=True, max_length=255)),
                ('intervention_at', models.DateTimeField(blank=True, null=True)),
                ('intervention', models.CharField(blank=True, max_length=255)),
                ('stood_down_at', models.DateTimeField(blank=True, null=True)),
                ('stood_down_reason', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='emergency.arrival')),
            ],
            options={
                'db_table': 'ed_critical_alert',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResuscitationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('arrest', 'Cardiac arrest'), ('cpr_start', 'CPR started'), ('cpr_stop', 'CPR stopped'), ('shock', 'Defibrillation'), ('drug', 'Drug given'), ('airway', 'Airway intervention'), ('access', 'Vascular access'), ('rhythm', 'Rhythm check'), ('rosc', 'Return of circulation'), ('procedure', 'Procedure'), ('observation', 'Observation'), ('death', 'Death declared')], max_length=24)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('drug', models.CharField(blank=True, max_length=128)),
                ('dose', models.CharField(blank=True, max_length=64)),
                ('route', models.CharField(blank=True, max_length=32)),
                ('joules', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rhythm', models.CharField(blank=True, max_length=64)),
                ('recorded_by_id', models.UUIDField(blank=True, null=True)),
                ('recorded_by_name', models.CharField(blank=True, max_length=255)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resuscitation', to='emergency.arrival')),
            ],
            options={
                'db_table': 'ed_resuscitation_event',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.IntegerField(choices=[(1, '1 — Resuscitation (immediate)'), (2, '2 — Emergent (within 10 minutes)'), (3, '3 — Urgent (within 30 minutes)'), (4, '4 — Less urgent (within 60 minutes)'), (5, '5 — Non-urgent (within 120 minutes)')])),
                ('previous_category', models.IntegerField(blank=True, null=True)),
                ('assessed_by_id', models.UUIDField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gcs', models.PositiveSmallIntegerField(blank=True, help_text='Glasgow Coma Scale, 3–15.', null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='emergency.arrival')),
            ],
            options={
                'db_table': 'ed_triage_assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['facility', 'disposition'], name='ed_arrival_facilit_a211e5_idx'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['disposition', 'triage_category', 'arrived_at'], name='ed_arrival_disposi_18889b_idx'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['patient', '-arrived_at'], name='ed_arrival_patient_06edb0_idx'),
        ),
        migrations.AddIndex(
            model_name='criticalalert',
            index=models.Index(fields=['pathway', '-activated_at'], name='ed_critical_pathway_e6cd6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='criticalalert',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('arrival', 'pathway'), name='uniq_alert_per_arrival_pathway'),
        ),
        migrations.AddIndex(
            model_name='resuscitationevent',
            index=models.Index(fields=['arrival', 'occurred_at'], name='ed_resuscit_arrival_f86728_idx'),
        ),
        migrations.AddIndex(
            model_name='triageassessment',
            index=models.Index(fields=['arrival', '-assessed_at'], name='ed_triage_a_arrival_52f82b_idx'),
        ),
    ]
