# Generated by Django 5.1.6 on 2026-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='arrived_unidentified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='arrival',
            name='identified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
