# Generated by Django 5.1.6 on 2026-09-04 04:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('login_identifier', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('locked', 'Locked'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='invited', max_length=12)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('wants_appointment_reminders', models.BooleanField(default=True)),
                ('wants_result_notifications', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='ne', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_account', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('looked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resource', models.CharField(max_length=32)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('via_proxy', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_log', to='patients.patient')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='portal.portalaccount')),
            ],
            options={
                'ordering': ['-looked_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code_hash', models.CharField(max_length=255)),
                ('code_hint', models.CharField(blank=True, max_length=8)),
                ('issued_by_id', models.UUIDField(blank=True, null=True)),
                ('issued_by_name', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('delivered_by', models.CharField(blank=True, max_length=24)),
                ('delivered_to', models.CharField(blank=True, max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='patients.patient')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('direction', models.CharField(choices=[('from_patient', 'From the patient'), ('to_patient', 'To the patient')], db_index=True, max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by_name', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='portal.portalaccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='patients.patient')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('token_hash', models.CharField(db_index=True, max_length=255)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('device_label', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='portal.portalaccount')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('relationship', models.CharField(choices=[('parent', 'Parent or guardian'), ('child', 'Adult child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('carer', 'Carer'), ('legal', 'Legal representative')], max_length=12)),
                ('can_see_results', models.BooleanField(default=False)),
                ('can_see_invoices', models.BooleanField(default=True)),
                ('can_book_appointments', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by_name', models.CharField(blank=True, max_length=255)),
                ('consent_evidence', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_name', models.CharField(blank=True, max_length=255)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='portal.portalaccount')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_grants', to='patients.patient')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalaccount',
            index=models.Index(fields=['status', '-last_login_at'], name='portal_port_status_ed23f0_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccesslog',
            index=models.Index(fields=['patient', '-looked_at'], name='portal_port_patient_5dfaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='portalaccesslog',
            index=models.Index(fields=['account', '-looked_at'], name='portal_port_account_02c561_idx'),
        ),
        migrations.AddIndex(
            model_name='portalinvitation',
            index=models.Index(fields=['patient', '-issued_at'], name='portal_port_patient_cdb62f_idx'),
        ),
        migrations.AddIndex(
            model_name='portalmessage',
            index=models.Index(fields=['patient', '-sent_at'], name='portal_port_patient_35571a_idx'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['account', '-issued_at'], name='portal_port_account_3bdb16_idx'),
        ),
        migrations.AddIndex(
            model_name='proxyaccess',
            index=models.Index(fields=['account', 'patient'], name='portal_prox_account_f7efad_idx'),
        ),
        migrations.AddConstraint(
            model_name='proxyaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('account', 'patient'), name='uniq_live_proxy_per_patient'),
        ),
    ]
