# Generated by Django 5.1.6 on 2026-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalinvitation',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
