# Generated by Django 5.1.6 on 2026-09-04 09:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_patientcorrectionrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientcorrectionrequest',
            new_name='portal_pati_patient_7f8b2a_idx',
            old_name='portal_pati_patient_77a9c1_idx',
        ),
        migrations.RenameIndex(
            model_name='patientcorrectionrequest',
            new_name='portal_pati_status_e77dc1_idx',
            old_name='portal_pati_status_94b1c2_idx',
        ),
        migrations.AddField(
            model_name='patientcorrectionrequest',
            name='deleted_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patientcorrectionrequest',
            name='updated_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='created_by_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='field_name',
            field=models.CharField(choices=[('phone', 'Phone number'), ('alternate_phone', 'Alternate phone'), ('email', 'Email'), ('temporary_address', 'Current / Temporary address'), ('tole', 'Tole / Street'), ('municipality', 'Municipality'), ('guardian_name', 'Emergency / Guardian name'), ('guardian_phone', 'Emergency / Guardian phone'), ('guardian_relationship', 'Emergency / Guardian relationship')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='patientcorrectionrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
