# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('diagnostic', 'Diagnostic centre'), ('warehouse', 'Warehouse'), ('corporate_office', 'Corporate office'), ('other', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('municipality', models.CharField(blank=True, max_length=128)),
                ('ward', models.CharField(blank=True, max_length=16)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('license_expires_on', models.DateField(blank=True, null=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('is_24x7', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('origin_reference', models.CharField(blank=True, max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.facility')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facility',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('clinical', 'Clinical'), ('diagnostic', 'Diagnostic'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('administrative', 'Administrative'), ('support', 'Support services'), ('finance', 'Finance'), ('operations', 'Operations')], default='clinical', max_length=32)),
                ('cost_centre_code', models.CharField(blank=True, max_length=32)),
                ('profit_centre_code', models.CharField(blank=True, max_length=32)),
                ('is_revenue_generating', models.BooleanField(default=True)),
                ('head_employee_uuid', models.UUIDField(blank=True, null=True)),
                ('phone_extension', models.CharField(blank=True, max_length=16)),
                ('location_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.facility')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['facility_id', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('facility', 'Facility'), ('department', 'Department')], db_index=True, max_length=16)),
                ('namespace', models.CharField(db_index=True, help_text='e.g. billing, pharmacy, payroll.', max_length=64)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('value', models.JSONField()),
                ('is_locked', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.facility')),
            ],
            options={
                'db_table': 'config_setting',
                'ordering': ['namespace', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Beds, chairs or counters, where meaningful.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='organization.department')),
            ],
            options={
                'db_table': 'unit',
                'ordering': ['department_id', 'display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type', 'status'], name='facility_facilit_d8f9b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('facility', 'code'), name='uniq_department_code_per_facility'),
        ),
        migrations.AddIndex(
            model_name='configsetting',
            index=models.Index(fields=['namespace', 'key', 'scope'], name='config_sett_namespa_45db5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='configsetting',
            constraint=models.UniqueConstraint(fields=('scope', 'facility', 'department', 'namespace', 'key'), name='uniq_config_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='uniq_unit_code_per_department'),
        ),
    ]
