# Generated by Django 5.1.6 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='configsetting',
            name='uniq_config_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='uniq_department_code_per_facility',
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='uniq_unit_code_per_department',
        ),
        migrations.AddConstraint(
            model_name='configsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('scope', 'facility', 'department', 'namespace', 'key'), name='uniq_config_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('facility', 'code'), name='uniq_department_code_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('department', 'code'), name='uniq_unit_code_per_department'),
        ),
    ]
