# Generated by Django 5.1.6 on 2026-09-14 19:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('date', models.DateField(db_index=True)),
                ('figures', models.JSONField(default=dict)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='organization.facility')),
            ],
            options={
                'db_table': 'org_daily_snapshot',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'facility'), name='uniq_snapshot_per_facility_day'), models.UniqueConstraint(condition=models.Q(('facility__isnull', True)), fields=('date',), name='uniq_organization_snapshot_per_day')],
            },
        ),
    ]
