# Generated by Django 5.1.6 on 2026-09-05 23:49

import apps.documents.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('clinical', 'Clinical record'), ('result', 'Diagnostic result'), ('imaging', 'Image or scan'), ('discharge', 'Discharge summary'), ('consent', 'Consent form'), ('identity', 'Identity or insurance'), ('employee', 'Employee record'), ('finance', 'Invoice or receipt'), ('other', 'Other')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('subject_type', models.CharField(db_index=True, max_length=48)),
                ('subject_uuid', models.UUIDField(db_index=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.documents.models.upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('uploaded_by_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_reason', models.CharField(blank=True, max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organization.facility')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.document')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_uuid', '-uploaded_at'], name='document_subject_e3aa34_idx'), models.Index(fields=['category', '-uploaded_at'], name='document_categor_d580d3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True)), fields=('subject_type', 'subject_uuid', 'checksum'), name='uniq_live_document_per_subject_and_content')],
            },
        ),
    ]
