# Generated by Django 5.1.6 on 2026-09-02 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('prescriber_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('prescriber_registration', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16)),
                ('prescribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision_reason', models.TextField(blank=True)),
                ('safety_checks', models.JSONField(blank=True, default=dict)),
                ('has_overridden_warning', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient_instructions', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='encounters.encounter')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='organization.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('product_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500 mg', max_length=64)),
                ('dosage_form', models.CharField(blank=True, help_text='Tablet, syrup, injection…', max_length=64)),
                ('dose', models.CharField(help_text='e.g. 1 tablet, 5 ml', max_length=64)),
                ('route', models.CharField(choices=[('PO', 'By mouth'), ('SL', 'Sublingual'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOP', 'Topical'), ('INH', 'Inhaled'), ('NEB', 'Nebulised'), ('PR', 'Rectal'), ('PV', 'Vaginal'), ('OPH', 'Into the eye'), ('OT', 'Into the ear'), ('NAS', 'Nasal'), ('IT', 'Intrathecal'), ('OTH', 'Other')], default='PO', max_length=8)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QDS', 'Four times daily'), ('QID', 'Four times daily'), ('NOCTE', 'At night'), ('MANE', 'In the morning'), ('STAT', 'Immediately, once'), ('PRN', 'As required'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('WEEKLY', 'Once weekly'), ('ALT', 'On alternate days'), ('OTHER', 'Other — see instructions')], default='BD', max_length=8)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_prn', models.BooleanField(default=False)),
                ('prn_indication', models.CharField(blank=True, max_length=255)),
                ('max_doses_per_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, help_text='e.g. after food, with water', max_length=512)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Course completed'), ('discontinued', 'Discontinued'), ('substituted', 'Substituted'), ('on_hold', 'On hold')], db_index=True, default='active', max_length=16)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('discontinued_by_id', models.UUIDField(blank=True, null=True)),
                ('discontinuation_reason', models.CharField(blank=True, max_length=512)),
                ('allow_substitution', models.BooleanField(default=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_line',
                'ordering': ['display_order', 'generic_name'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_at'], name='prescriptio_patient_8f8767_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', '-prescribed_at'], name='prescriptio_status_e6b0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescriber_id', '-prescribed_at'], name='prescriptio_prescri_d94af3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionline',
            index=models.Index(fields=['prescription', 'status'], name='prescriptio_prescri_2bc74a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionline',
            index=models.Index(fields=['generic_name'], name='prescriptio_generic_f1c66a_idx'),
        ),
    ]
