# Generated by Django 5.1.6 on 2026-09-05 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('presented_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('presented_to_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('presented_to_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presented_prescriptions', to='organization.facility')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_presentation',
                'ordering': ['-presented_at'],
                'indexes': [models.Index(fields=['facility', 'is_active', '-presented_at'], name='prescriptio_facilit_38e3b3_idx'), models.Index(fields=['prescription', 'is_active'], name='prescriptio_prescri_a4333f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('prescription', 'facility'), name='uniq_live_presentation_per_pharmacy')],
            },
        ),
    ]
