# Generated by Django 5.1.6 on 2026-09-14 15:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('prescriptions', '0002_prescription_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('patient_instructions', models.TextField(blank=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_templates', to='organization.department')),
            ],
            options={
                'db_table': 'prescription_template',
                'ordering': ['-times_used', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('product_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('strength', models.CharField(blank=True, max_length=64)),
                ('dosage_form', models.CharField(blank=True, max_length=32)),
                ('dose', models.CharField(help_text='e.g. 1 tablet, 5 ml', max_length=64)),
                ('route', models.CharField(choices=[('PO', 'By mouth'), ('SL', 'Sublingual'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOP', 'Topical'), ('INH', 'Inhaled'), ('NEB', 'Nebulised'), ('PR', 'Rectal'), ('PV', 'Vaginal'), ('OPH', 'Into the eye'), ('OT', 'Into the ear'), ('NAS', 'Nasal'), ('IT', 'Intrathecal'), ('OTH', 'Other')], default='PO', max_length=16)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily'), ('BD', 'Twice daily'), ('TDS', 'Three times daily'), ('QDS', 'Four times daily'), ('QID', 'Four times daily'), ('NOCTE', 'At night'), ('MANE', 'In the morning'), ('STAT', 'Immediately, once'), ('PRN', 'As required'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('WEEKLY', 'Once weekly'), ('ALT', 'On alternate days'), ('OTHER', 'Other — see instructions')], default='BD', max_length=8)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_prn', models.BooleanField(default=False)),
                ('prn_indication', models.CharField(blank=True, max_length=255)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='prescriptions.prescriptiontemplate')),
            ],
            options={
                'db_table': 'prescription_template_line',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['owner_id', 'is_active'], name='prescriptio_owner_i_537051_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['-times_used'], name='prescriptio_times_u_9cb704_idx'),
        ),
    ]
