# Generated by Django 5.1.6 on 2026-09-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='note_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='note_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='note_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='note_subjective',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClinicalTemplateInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(db_index=True, max_length=32)),
                ('test_name', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(default='routine', max_length=16)),
                ('clinical_indication', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='prescriptions.prescriptiontemplate')),
            ],
            options={
                'db_table': 'clinical_template_investigation',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
