# Generated by Django 5.1.6 on 2026-09-02 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.000'), help_text='Percentage. Zero for VAT-exempt items.', max_digits=5),
        ),
    ]
