# Generated by Django 5.1.6 on 2026-09-09 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_product_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('dispatched', 'Sent, not yet received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='dispatched', max_length=16)),
                ('dispatched_by_id', models.UUIDField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_by_id', models.UUIDField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=512)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='pharmacy.stocklocation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='pharmacy.stocklocation')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('quantity_sent', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='pharmacy.batch')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.stocktransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', '-dispatched_at'], name='pharmacy_st_status_a3e888_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination', 'status'], name='pharmacy_st_destina_2967fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('transfer', 'batch'), name='transfer_batch_once'),
        ),
    ]
