# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequestPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('allow_self_service_within_quota', models.BooleanField(default=True)),
                ('require_org_approval_for_open', models.BooleanField(default=True)),
                ('require_org_approval_for_close', models.BooleanField(default=True)),
                ('require_platform_approval_for_close', models.BooleanField(default=False)),
                ('churn_window_days', models.PositiveSmallIntegerField(default=90)),
                ('churn_threshold', models.PositiveSmallIntegerField(default=2)),
                ('auto_expire_days', models.PositiveSmallIntegerField(default=30)),
                ('enforce_segregation_of_duties', models.BooleanField(default=True)),
                ('require_justification', models.BooleanField(default=True)),
                ('min_justification_length', models.PositiveSmallIntegerField(default=40)),
                ('organization', models.OneToOneField(blank=True, help_text='NULL for the platform-wide default policy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_request_policy', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_change_request_policy',
            },
        ),
        migrations.CreateModel(
            name='FacilityChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(help_text='Human-quotable, e.g. FCR-2026-0041.', max_length=32, unique=True)),
                ('request_type', models.CharField(choices=[('open_facility', 'Open a facility'), ('close_facility', 'Close a facility'), ('reopen_facility', 'Re-open a closed facility'), ('suspend_facility', 'Suspend a facility'), ('resume_facility', 'Resume a suspended facility'), ('convert_type', "Change a facility's type"), ('transfer_facility', 'Move a facility to another organization')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('org_review', 'Awaiting organization approval'), ('platform_review', 'Awaiting platform approval'), ('info_requested', 'More information requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('scheduled', 'Approved, scheduled for a future date'), ('executed', 'Executed'), ('failed', 'Execution failed'), ('expired', 'Expired without a decision')], db_index=True, default='draft', max_length=24)),
                ('approval_level', models.CharField(choices=[('automatic', 'No approval needed'), ('organization', 'Organization administrator'), ('platform', 'Platform staff'), ('both', 'Organization, then platform')], default='organization', max_length=16)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('diagnostic', 'Diagnostic centre'), ('warehouse', 'Warehouse'), ('corporate_office', 'Corporate office'), ('other', 'Other')], max_length=32)),
                ('target_facility_uuid', models.UUIDField(blank=True, null=True)),
                ('proposed_name', models.CharField(blank=True, max_length=255)),
                ('proposed_code', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('requested_effective_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('quota_evaluation', models.JSONField(blank=True, default=dict)),
                ('requires_capacity_purchase', models.BooleanField(default=False)),
                ('proposed_addon_code', models.CharField(blank=True, max_length=64)),
                ('proposed_addon_quantity', models.PositiveIntegerField(default=0)),
                ('estimated_price_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('escalation_reasons', models.JSONField(blank=True, default=list)),
                ('churn_signal', models.JSONField(blank=True, default=dict)),
                ('requested_by_id', models.UUIDField(blank=True, null=True)),
                ('requested_by_email', models.CharField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_error', models.TextField(blank=True)),
                ('resulting_facility_uuid', models.UUIDField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_change_requests', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_facility_change_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('level', models.CharField(choices=[('automatic', 'No approval needed'), ('organization', 'Organization administrator'), ('platform', 'Platform staff'), ('both', 'Organization, then platform')], max_length=16)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_info', 'Request more information'), ('escalate', 'Escalate'), ('withdraw', 'Withdraw')], max_length=16)),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('decided_by_email', models.CharField(blank=True, max_length=254)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('granted_addon_code', models.CharField(blank=True, max_length=64)),
                ('granted_addon_quantity', models.PositiveIntegerField(default=0)),
                ('granted_entitlement_delta', models.IntegerField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='provisioning.facilitychangerequest')),
            ],
            options={
                'db_table': 'cp_change_request_decision',
                'ordering': ['decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('author_email', models.CharField(blank=True, max_length=254)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='provisioning.facilitychangerequest')),
            ],
            options={
                'db_table': 'cp_change_request_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='facilitychangerequest',
            index=models.Index(fields=['organization', 'status'], name='cp_facility_organiz_63bcc4_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitychangerequest',
            index=models.Index(fields=['status', 'approval_level'], name='cp_facility_status_5bb1c8_idx'),
        ),
    ]
