# Generated by Django 5.1.6 on 2026-09-11 03:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
        ('tenancy', '0002_remove_facilityregistryentry_uniq_facility_code_per_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(db_index=True, max_length=32)),
                ('pan_number', models.CharField(blank=True, max_length=32)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('facility_count', models.PositiveSmallIntegerField(default=1)),
                ('bed_count', models.PositiveIntegerField(default=0)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('current_system', models.CharField(blank=True, max_length=128)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_role', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('onboarded', 'Onboarded'), ('declined', 'Declined')], db_index=True, default='new', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('reviewed_by_email', models.CharField(blank=True, max_length=254)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_registration_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
