# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('meter_key', models.CharField(db_index=True, max_length=64)),
                ('limit_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('period', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('billing_period', 'Billing period'), ('lifetime', 'Lifetime')], default='month', max_length=16)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('peak_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('overage', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Closed periods are frozen for billing.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_usage_counter',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['organization', 'meter_key', '-period_start'], name='cp_usage_co_organiz_699d13_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'meter_key', 'period', 'period_start'), name='uniq_usage_counter_period')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('meter_key', models.CharField(db_index=True, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('facility_uuid', models.UUIDField(blank=True, null=True)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_usage_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'meter_key', '-occurred_at'], name='cp_usage_ev_organiz_01cd75_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization', 'meter_key', 'idempotency_key'), name='uniq_usage_event_idempotency')],
            },
        ),
    ]
