# Generated by Django 5.1.6 on 2026-09-14 20:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('system', models.CharField(choices=[('icd10', 'ICD-10'), ('local', 'Local')], default='icd10', max_length=16)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.CharField(blank=True, max_length=64)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('is_common', models.BooleanField(db_index=True, default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'terminology_diagnosis_code',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_common', '-times_used'], name='terminology_is_comm_d5ffd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('system', 'code'), name='uniq_code_per_system')],
            },
        ),
    ]
