# Generated by Django 5.1.6 on 2026-09-10 02:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('patients', 'Patients'), ('employees', 'Employees'), ('medicines', 'Medicines and products'), ('suppliers', 'Suppliers'), ('services', 'Services and prices')], db_index=True, max_length=24)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded, not yet mapped'), ('mapped', 'Columns mapped'), ('validated', 'Validated, ready to preview'), ('imported', 'Imported'), ('partial', 'Imported with failures'), ('cancelled', 'Cancelled')], db_index=True, default='uploaded', max_length=16)),
                ('headers', models.JSONField(default=list)),
                ('column_map', models.JSONField(default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(default=dict)),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=255)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dataimport_batch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='dataimport__kind_4e0c4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', models.JSONField(default=dict)),
                ('normalised', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Not yet validated'), ('valid', 'Ready to import'), ('invalid', 'Cannot be imported'), ('duplicate', 'Matches an existing record'), ('imported', 'Imported'), ('skipped', 'Deliberately not imported'), ('failed', 'Import was attempted and failed')], db_index=True, default='pending', max_length=12)),
                ('decision', models.CharField(choices=[('undecided', 'Awaiting a decision'), ('import', 'Import anyway'), ('skip', 'Skip this row')], default='undecided', max_length=12)),
                ('errors', models.JSONField(default=list)),
                ('duplicate_of_uuid', models.UUIDField(blank=True, null=True)),
                ('duplicate_of_label', models.CharField(blank=True, max_length=255)),
                ('duplicate_score', models.PositiveSmallIntegerField(default=0)),
                ('duplicate_matched_on', models.JSONField(default=list)),
                ('duplicate_of_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_uuid', models.UUIDField(blank=True, null=True)),
                ('created_label', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, max_length=512)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='dataimport.importbatch')),
            ],
            options={
                'db_table': 'dataimport_row',
                'ordering': ['batch_id', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'status'], name='dataimport__batch_i_2918b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('batch', 'row_number'), name='uniq_import_row_per_batch')],
            },
        ),
    ]
