# Generated by Django 5.1.6 on 2026-09-02 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('delta', models.IntegerField(help_text='Added to the resolved limit.')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL means it does not expire on its own.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('granted_by_id', models.UUIDField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_entitlement_grant',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['organization', 'key'], name='cp_entitlem_organiz_f3352a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('limit', 'Limit value'), ('module', 'Module access'), ('feature', 'Feature flag')], max_length=16)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(blank=True, null=True)),
                ('enforcement', models.CharField(blank=True, choices=[('hard', 'Block the action'), ('soft', 'Allow, flag for review'), ('grace', 'Allow within grace window, then block'), ('metered', 'Allow and bill the overage')], max_length=16)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Why this customer deviates from their plan. Required.')),
                ('contract_reference', models.CharField(blank=True, max_length=128)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_overrides', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_entitlement_override',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['organization', 'kind', 'key'], name='cp_entitlem_organiz_a6bc45_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('resolved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('plan_code', models.CharField(max_length=64)),
                ('subscription_status', models.CharField(max_length=16)),
                ('modules', models.JSONField(default=dict)),
                ('features', models.JSONField(default=dict)),
                ('limits', models.JSONField(default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('triggering_reason', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_snapshots', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cp_entitlement_snapshot',
                'ordering': ['-resolved_at'],
                'indexes': [models.Index(fields=['organization', '-resolved_at'], name='cp_entitlem_organiz_58bf46_idx')],
            },
        ),
    ]
