# Generated by Django 5.1.6 on 2026-09-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_nursing_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicationadministration',
            new_name='ipd_medicat_admissi_65b314_idx',
            old_name='ipd_med_adm_admissi_4a11f2_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationadministration',
            new_name='ipd_medicat_prescri_3ab43e_idx',
            old_name='ipd_med_adm_prescri_9b32c8_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationadministration',
            new_name='ipd_medicat_status_806fcb_idx',
            old_name='ipd_med_adm_status_8c17b0_idx',
        ),
        migrations.RenameIndex(
            model_name='nurseassignment',
            new_name='ipd_nurse_a_nurse_i_94f991_idx',
            old_name='ipd_nurse_a_nurse_i_9a1e01_idx',
        ),
        migrations.RenameIndex(
            model_name='nurseassignment',
            new_name='ipd_nurse_a_ward_id_3b8ec1_idx',
            old_name='ipd_nurse_a_ward_id_24a49c_idx',
        ),
        migrations.RenameIndex(
            model_name='nurseassignment',
            new_name='ipd_nurse_a_admissi_793943_idx',
            old_name='ipd_nurse_a_admissi_3ef418_idx',
        ),
        migrations.RenameIndex(
            model_name='nursinghandover',
            new_name='ipd_nursing_admissi_2d2d10_idx',
            old_name='ipd_nursing_admissi_7e11aa_idx',
        ),
        migrations.RenameIndex(
            model_name='nursinghandover',
            new_name='ipd_nursing_ward_id_81a814_idx',
            old_name='ipd_nursing_ward_id_81f2bb_idx',
        ),
        migrations.RenameIndex(
            model_name='nursinghandover',
            new_name='ipd_nursing_is_ackn_9b8a70_idx',
            old_name='ipd_nursing_is_ackn_49a901_idx',
        ),
        migrations.RenameIndex(
            model_name='nursingtask',
            new_name='ipd_nursing_admissi_ce3f80_idx',
            old_name='ipd_nursing_admissi_201ab4_idx',
        ),
        migrations.RenameIndex(
            model_name='nursingtask',
            new_name='ipd_nursing_ward_id_82cf2f_idx',
            old_name='ipd_nursing_ward_id_651a2d_idx',
        ),
        migrations.RenameIndex(
            model_name='nursingtask',
            new_name='ipd_nursing_status_9234c4_idx',
            old_name='ipd_nursing_status_8818f1_idx',
        ),
    ]
