# Generated by Django 5.1.6 on 2026-09-14 19:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_nursing_index_names'),
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharge_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_diet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_warning_signs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DischargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('course', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('diet', models.TextField(blank=True)),
                ('activity', models.TextField(blank=True)),
                ('warning_signs', models.JSONField(blank=True, default=list)),
                ('follow_up_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_templates', to='organization.department')),
            ],
            options={
                'db_table': 'ipd_discharge_template',
                'ordering': ['name'],
            },
        ),
    ]
