# Generated by Django 5.1.6 on 2026-09-02 07:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_remove_configsetting_uniq_config_per_scope_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('provider_uuid', models.UUIDField(db_index=True)),
                ('provider_name', models.CharField(help_text='Denormalised for display; employees live in a module that does not exist yet.', max_length=255)),
                ('provider_speciality', models.CharField(blank=True, max_length=128)),
                ('room', models.CharField(blank=True, max_length=64)),
                ('weekday', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('slot_capacity', models.PositiveSmallIntegerField(default=1)),
                ('walk_in_reserve', models.PositiveSmallIntegerField(default=0)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_accepting_online', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_schedules', to='organization.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_schedules', to='organization.facility')),
            ],
            options={
                'db_table': 'provider_schedule',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('provider_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('arrived', 'Patient arrived'), ('in_consultation', 'In consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'Did not attend'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('counter', 'Booked at counter'), ('phone', 'Telephone'), ('online', 'Patient portal'), ('mobile', 'Mobile app'), ('referral', 'Referral'), ('follow_up', 'Follow-up')], default='counter', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by_id', models.UUIDField(blank=True, null=True)),
                ('booked_by_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='organization.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='organization.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('previous_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='scheduling.appointment')),
                ('rescheduled_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='scheduling.appointment')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.providerschedule')),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('token_number', models.CharField(db_index=True, max_length=16)),
                ('queue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('provider_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('counter', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_service', 'In consultation'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('left', 'Left without being seen'), ('transferred', 'Transferred')], db_index=True, default='waiting', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_emergency', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('call_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_token', to='scheduling.appointment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='organization.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='organization.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_tokens', to='patients.patient')),
            ],
            options={
                'db_table': 'queue_token',
                'ordering': ['-priority', 'issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('provider_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('exception_date', models.DateField(db_index=True)),
                ('is_unavailable', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.facility')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='scheduling.providerschedule')),
            ],
            options={
                'db_table': 'schedule_exception',
                'ordering': ['-exception_date'],
            },
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['provider_uuid', 'weekday'], name='provider_sc_provide_b528a1_idx'),
        ),
        migrations.AddIndex(
            model_name='providerschedule',
            index=models.Index(fields=['facility', 'weekday', 'is_active'], name='provider_sc_facilit_595858_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['facility', 'scheduled_for', 'status'], name='appointment_facilit_624e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider_uuid', 'scheduled_for'], name='appointment_provide_1540c1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-scheduled_for'], name='appointment_patient_c714eb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_for'], name='appointment_status_bf7c79_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['facility', 'queue_date', 'status'], name='queue_token_facilit_9fdb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['department', 'queue_date', 'status'], name='queue_token_departm_bcb52b_idx'),
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['status', '-priority', 'issued_at'], name='queue_token_status_350815_idx'),
        ),
        migrations.AddConstraint(
            model_name='queuetoken',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('facility', 'queue_date', 'token_number'), name='uniq_token_per_facility_day'),
        ),
        migrations.AddIndex(
            model_name='scheduleexception',
            index=models.Index(fields=['exception_date', 'provider_uuid'], name='schedule_ex_excepti_51fec5_idx'),
        ),
    ]
