# Generated by Django 5.1.6 on 2026-09-02 07:22

import apps.identity.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=128)),
                ('avatar_url', models.URLField(blank=True)),
                ('locale', models.CharField(default='en-NP', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_platform_staff', models.BooleanField(default=False)),
                ('support_access_enabled', models.BooleanField(default=False)),
                ('support_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cp_user',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(db_index=True, max_length=254)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('bad_credentials', 'Bad credentials'), ('mfa_required', 'MFA required'), ('mfa_failed', 'MFA failed'), ('locked', 'Account locked'), ('inactive', 'Account inactive'), ('no_organization', 'No organization')], db_index=True, max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_login_attempt',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', '-attempted_at'], name='cp_login_at_email_907c84_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], db_index=True, default='invited', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_organization_owner', models.BooleanField(default=False)),
                ('employee_uuid', models.UUIDField(blank=True, null=True)),
                ('facility_uuids', models.JSONField(blank=True, default=list)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by_id', models.UUIDField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consumes_seat', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_membership',
                'ordering': ['organization_id', 'user_id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='cp_membersh_organiz_ac7882_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership_per_org'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_membership_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_user_device',
                'ordering': ['-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_device_per_user')],
            },
        ),
    ]
