# Generated by Django 5.1.6 on 2026-09-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0002_remove_facilityregistryentry_uniq_facility_code_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_membership_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='userdevice',
            name='uniq_device_per_user',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'organization'), name='uniq_membership_per_org'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'device_id'), name='uniq_device_per_user'),
        ),
    ]
