# Generated by Django 5.1.6 on 2026-09-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_mfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('bad_credentials', 'Bad credentials'), ('mfa_required', 'MFA required'), ('mfa_failed', 'MFA failed'), ('locked', 'Account locked'), ('inactive', 'Account inactive'), ('no_organization', 'No organization'), ('reset_requested', 'Password reset requested'), ('password_reset', 'Password reset by email')], db_index=True, max_length=24),
        ),
    ]
